#!/usr/bin/env bash

# Delete first 23 characters
request=${1:23}

# Decode URL
request=$(echo $request | echo -e "$(sed 's/+/ /g; s/%/\\x/g')")

# Replace &line= with :
request=${request/&line=/:}

# Replace &column= with :
request=${request/&column=/:}

# Launch Editors

# If sublime is running
if [ -n "`pidof sublime_text`" ]; then
    subl $request
fi

# If code is running
if [ -n "`pidof code`" ]; then
    code -g $request
fi

# If none running, open sublime
if [ -z "`pidof sublime_text``pidof code`" ]; then
    subl $request
fi
